language: node_js
node_js:
  - "stable"
  - "7"
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
after_success:
  - npm run coverage
  - npm run build
